site_name: GSO GTS 2023 Phuket
site_url: https://github.com/nutanix-japan/gsolanding
site_author: Lakshmi Balaramane

# Repository

repo_name: nutanix-japan/ntnxclusctl
repo_url: https://github.com/nutanix-japan/gsolanding

# Copyright
copyright: Copyright &copy; 2016 - 2023 Nutanix APAC Enablement Practice

# Configuration

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
  - content.code.copy
  - content.code.annotate
  - navigation.instant
  - navigation.tracking
  # - navigation.sections # leave this commented for sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - navigation.integrate
  - search.highlight
  - search.suggest
  - toc.follow
  palette:

    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
    - search

# Style sheeting here
# extra_css:
#   - stylesheets/extra.css

nav:
    - 'Overview': index.md
    - 'Cluster Lookup': cluster_lookup/cluster_lookup.md
    - 'Labs': gts_labs/gts_labs.md
    - 'Code of Conduct': code_conduct/code_conduct.md